name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # 先生成 package-lock.json
    - run: npm install
    
    # 然后使用 ci 进行干净安装
    - run: npm ci  # Use ci instead of install for cleaner builds
    
    - name: Build
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        npm install
        npm run build
