name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # 验证 package.json 是否存在并格式正确
    - name: 验证 package.json
      run: |
        if [ ! -f package.json ]; then
          echo "package.json 文件不存在"
          exit 1
        fi
        if ! jq empty package.json; then
          echo "package.json 格式错误"
          exit 1
        fi
    
    # 自动生成 package-lock.json（如果不存在）
    - name: 初始化 npm 环境
      run: |
        if [ ! -f package-lock.json ]; then
          npm install
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package-lock.json
          git commit -m "自动生成 package-lock.json" || echo "没有新的 package-lock.json 需要提交"
        fi
    
    # 安装依赖
    - run: npm ci
    
    # 清理构建目录并确保构建成功
    - name: 构建项目

      run: |
        echo "SUPABASE_URL: ${{ secrets.SUPABASE_URL }}"
        echo "SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}"
        if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
          echo "SUPABASE_URL 未配置或为空"
          exit 1
        fi
        if [ -z "${{ secrets.SUPABASE_KEY }}" ]; then
          echo "SUPABASE_KEY 未配置或为空"
          exit 1
        fi
       
        if [ -d dist ]; then
          echo "清理 dist 目录中..."
          rm -rf dist
        fi
        if ! npm run build; then
          echo "构建失败"
          exit 1
        fi
        echo "构建完成，无需输出目录"