name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # 验证环境变量是否配置
    - name: 验证环境变量
      run: |
        if [ -z "${{ secrets.SUPABASE_URL }}" ]; then
          echo "::error::SUPABASE_URL 未配置"
          exit 1
        fi
        if [ -z "${{ secrets.SUPABASE_KEY }}" ]; then
          echo "::error::SUPABASE_KEY 未配置"
          exit 1
        fi
    
    # 创建配置目录
    - name: 创建配置目录
      run: mkdir -p js
    
    # 生成前端配置文件
    - name: 生成配置文件
      run: |
        echo "// 自动生成的配置文件" > js/config.js
        echo "window.__SUPABASE_CONFIG__ = {" >> js/config.js
        echo "  url: '${{ secrets.SUPABASE_URL }}'," >> js/config.js
        echo "  key: '${{ secrets.SUPABASE_KEY }}'" >> js/config.js
        echo "};" >> js/config.js
        
        # 验证文件是否生成成功
        if [ ! -f js/config.js ]; then
          echo "::error::配置文件生成失败"
          exit 1
        fi
    
    # 验证 package.json
    - name: 验证 package.json
      run: |
        if [ ! -f package.json ]; then
          echo "package.json 文件不存在"
          exit 1
        fi
        if ! jq empty package.json; then
          echo "package.json 格式错误"
          exit 1
        fi
    
    # 先运行npm install生成package-lock.json
    - name: 生成package-lock.json
      run: npm install
    
    # 然后运行npm ci
    - name: 安装依赖
      run: npm ci
    
    # 构建项目
    - name: 构建项目
      run: |
        # 使用sed替换模板文件中的占位符
        sed -i "s|{{SUPABASE_URL}}|${{ secrets.SUPABASE_URL }}|g" public/config.template.js
        sed -i "s|{{SUPABASE_KEY}}|${{ secrets.SUPABASE_KEY }}|g" public/config.template.js
        mv public/config.template.js public/config.js
        
        npm run build

        # 确保配置文件被复制到dist目录
        if [ ! -f dist/js/config.js ]; then
          mkdir -p dist/js
          cp js/config.js dist/js/
        fi

        echo "构建完成，配置文件已包含"