name: Deploy Static App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Debug print secrets
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "SUPABASE_URL: $SUPABASE_URL"
        echo "SUPABASE_KEY: $SUPABASE_KEY"
      
    - name: Inject environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      shell: bash
      run: |
        # 直接在index.html文件末尾添加脚本
        echo '<script>window.SUPABASE_URL="$SUPABASE_URL";window.SUPABASE_KEY="$SUPABASE_KEY";</script>' >> index.html
    
    - name: Check index.html content
      run: |
        cat index.html