name: Deploy Static App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Clean install
      run: |
        rm -rf node_modules
        npm cache clean --force
        npm install --no-optional --no-shrinkwrap --no-package-lock

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build project
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        # 生成env-config.js到public目录
        mkdir -p public
        echo "window.SUPABASE_URL = '$SUPABASE_URL';" > public/env-config.js
        echo "window.SUPABASE_KEY = '$SUPABASE_KEY';" >> public/env-config.js
        
        # 检查文件是否生成
        ls -la public/
        cat public/env-config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # 发布public目录
        keep_files: true  # 保留生成的文件