name: Deploy Static App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Clean install
      run: |
        rm -rf node_modules
        npm cache clean --force
        npm install --no-optional --no-shrinkwrap --no-package-lock

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build project
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "window.SUPABASE_URL = '$SUPABASE_URL';" > env-config.js
        echo "window.SUPABASE_KEY = '$SUPABASE_KEY';" >> env-config.js
        echo "Build step skipped for static app"
        npm run build
        rm -rf node_modules

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./