name: Deploy Static App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup public directory
      run: |
        mkdir -p public
        cp -r js public/
        cp -r css public/
        cp index.html public/

    - name: Generate environment config inline
      run: |
        echo "window.SUPABASE_URL='${{ secrets.SUPABASE_URL }}';window.SUPABASE_KEY='${{ secrets.SUPABASE_KEY }}';" > public/js/env.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public