name: Deploy Static App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Debug print secrets
      run: |
        echo "SUPABASE_URL: ${{ secrets.SUPABASE_URL }}"
        echo "SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}"
      
    - name: Inject environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        script_content="<script>window.SUPABASE_URL=\"$SUPABASE_URL\";window.SUPABASE_KEY=\"$SUPABASE_KEY\";</script>"
        echo "$script_content" >> index.html
    
    - name: Check index.html content
      run: |
        cat index.html