name: Deploy Static App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Debug print secrets
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        echo "SUPABASE_URL: $SUPABASE_URL"
        echo "SUPABASE_KEY: $SUPABASE_KEY"
      
    - name: Inject environment variables
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      shell: bash
      run: |
        # 直接创建脚本内容
        script_content="<script>window.SUPABASE_URL=\"$SUPABASE_URL\";window.SUPABASE_KEY=\"$SUPABASE_KEY\";</script>"
        # 使用 sed 命令将脚本插入到 </body> 标签之前
        echo "$script_content" >> temp.html
        cat index.html >> temp.html
        mv temp.html index.html
    
    - name: Check index.html content
      run: |
        cat index.html